name: Send Mails to Telegram

on:
  workflow_dispatch:
    
jobs:
  send:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mail_telegram_core
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo run