name: Send Mails to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  send:
    environment: my-deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mail_telegram_core
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_MY_CHAT_ID: ${{ secrets.TELEGRAM_MY_CHAT_ID }}
      GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: browser-actions/setup-chrome@v1
      - uses: dtolnay/rust-toolchain@stable
      - run: RUST_BACKTRACE=1 cargo run